apiVersion: v1
kind: Service
metadata:
  name: devops-web
spec:
  selector:
    app: devops-web
  ports:
    - protocol: TCP
      port: 3000
      targetPort: 3000
  type: LoadBalancer
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: devops-web
spec:
  replicas: 1
  selector:
    matchLabels:
      app: devops-web
  template:
    metadata:
      labels:
        app: devops-web
    spec:
      containers:
      - name: devops-web
        image: karabalta75/web-app:1.0.0
        ports:
        - containerPort: 3000
        readinessProbe:
          httpGet:
            path: /
            port: 3000
          initialDelaySeconds: 5
          periodSeconds: 10
        livenessProbe:
          httpGet:
            path: /
            port: 3000
          initialDelaySeconds: 5
          periodSeconds: 20        
        env:
        - name: API_HOST
          valueFrom:
            configMapKeyRef:
              name: devops-web-config
              key: API_HOST
        - name: PORT
          valueFrom:
            configMapKeyRef:
              name: devops-web-config
              key: PORT
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: devops-web-config
data:
  API_HOST: http://devops-api:3001
  PORT: "3000"